name: Tests
on: [ workflow_call, workflow_dispatch ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20.x'
      - run: yarn install --immutable
      - run: yarn test:main
      - run: yarn test:preload
      - run: yarn test:renderer
      - run: yarn test:e2e
